import "./globals.css";

export const metadata = {
  title: "Green Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#1b211d] w-full h-screen flex justify-center py-8 overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
